"""Medical guidelines and reference constants for health scoring engine."""

# BMI Reference Ranges (WHO Guidelines)
BMI_UNDERWEIGHT_UPPER = 18.5
BMI_NORMAL_UPPER = 24.9
BMI_OVERWEIGHT_UPPER = 29.9

# Blood Pressure Reference Ranges (AHA Guidelines)
BP_SYSTOLIC_NORMAL_UPPER = 120
BP_SYSTOLIC_ELEVATED_UPPER = 129
BP_SYSTOLIC_STAGE1_UPPER = 139

BP_DIASTOLIC_NORMAL_UPPER = 80
BP_DIASTOLIC_STAGE1_UPPER = 89

# Fasting Glucose (ADA Guidelines - mg/dL)
GLUCOSE_NORMAL_UPPER = 99.0
GLUCOSE_PREDIABETES_UPPER = 125.0

# Cholesterol Guidelines (NCEP ATP III - mg/dL)
CHOLESTEROL_TOTAL_DESIRABLE_UPPER = 200.0
CHOLESTEROL_TOTAL_BORDERLINE_UPPER = 239.0

HDL_LOW_MALE = 40.0
HDL_LOW_FEMALE = 50.0
HDL_OPTIMAL_LOWER = 60.0

LDL_OPTIMAL_UPPER = 100.0
LDL_NEAR_OPTIMAL_UPPER = 129.0
LDL_BORDERLINE_UPPER = 159.0
LDL_HIGH_UPPER = 189.0

# Lifestyle Recommendations
EXERCISE_RECOMMENDED_MIN_HOURS = 2.5
EXERCISE_RECOMMENDED_MAX_HOURS = 5.0

SLEEP_RECOMMENDED_MIN_HOURS = 7.0
SLEEP_RECOMMENDED_MAX_HOURS = 9.0

WATER_RECOMMENDED_MIN_LITERS = 2.0
WATER_RECOMMENDED_MAX_LITERS = 3.5

STRESS_LOW_THRESHOLD = 3
STRESS_MODERATE_THRESHOLD = 6

# Scoring Weights
CARDIOVASCULAR_WEIGHT = 0.40
METABOLIC_WEIGHT = 0.35
LIFESTYLE_WEIGHT = 0.25
